// src/StaticMovies.jsx
const staticMovies = [
  {
    id: "s1",
    title: "The Dark Knight",
    release_date: "2008-07-18",
    vote_average: 9.0,
    overview: "Batman battles the Joker in Gotham City.",
    poster_path: "/1.png",
  },
  {
    id: "s2",
    title: "Inception",
    release_date: "2010-07-16",
    vote_average: 8.8,
    overview: "A thief steals secrets by entering dreams.",
    poster_path: "/images/2.png",
  },
  {
    id: "s3",
    title: "Interstellar",
    release_date: "2014-11-07",
    vote_average: 8.6,
    overview: "Explorers travel through a wormhole to save humanity.",
    poster_path: "/images/3.png",
  },
  {
    id: "s4",
    title: "Avengers: Endgame",
    release_date: "2019-04-26",
    vote_average: 8.4,
    overview: "The Avengers assemble to reverse the damage caused by Thanos.",
    poster_path: "/images/4.png",
  },
  {
    id: "s5",
    title: "Titanic",
    release_date: "1997-12-19",
    vote_average: 7.8,
    overview: "A love story unfolds aboard the ill-fated RMS Titanic.",
    poster_path: "/images/5.png",
  },
  {
    id: "s6",
    title: "Avatar",
    release_date: "2009-12-18",
    vote_average: 7.8,
    overview: "Humans invade Pandora, a lush alien planet, seeking resources.",
    poster_path: "/images/6.png",
  },
  {
    id: "s7",
    title: "Joker",
    release_date: "2019-10-04",
    vote_average: 8.5,
    overview: "Arthur Fleck becomes the infamous Joker in Gotham City.",
    poster_path: "/images/7.png",
  },
  {
    id: "s8",
    title: "Spider-Man: No Way Home",
    release_date: "2021-12-17",
    vote_average: 8.3,
    overview: "Peter Parker deals with multiverse villains after revealing his identity.",
    poster_path: "/images/8.png",
  },
  {
    id: "s9",
    title: "Black Panther",
    release_date: "2018-02-16",
    vote_average: 7.3,
    overview: "T'Challa returns to Wakanda to claim the throne and protect his people.",
    poster_path: "/images/9.png",
  },
  {
    id: "s10",
    title: "Guardians of the Galaxy",
    release_date: "2014-08-01",
    vote_average: 8.0,
    overview: "A group of intergalactic criminals must save the galaxy.",
    poster_path: "/images/10.png",
  },
  {
    id: "s11",
    title: "Frozen II",
    release_date: "2019-11-22",
    vote_average: 7.3,
    overview: "Elsa and Anna set out on a journey to discover the origin of Elsa’s powers.",
    poster_path: "/images/11.png",
  },
  {
    id: "s12",
    title: "Doctor Strange",
    release_date: "2016-11-04",
    vote_average: 7.5,
    overview: "A neurosurgeon embarks on a journey of healing and mystical discovery.",
    poster_path: "/images/12.png",
  },
];

export default staticMovies;
